[package]
name = "gotham-middleware-threadpool"
version = "0.1.0"
authors = ["Christoph Wurst <christoph@winzerhof-wurst.at>"]

[dependencies]
futures-cpupool = "0.1.8"
gotham = "^0.2"
gotham_derive = "^0.2"

[dev-dependencies]
futures = "*"
hyper = "*"
mime = "*"
